version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nexcore-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nexcore
      POSTGRES_USER: nexcore
      POSTGRES_PASSWORD: nexcore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
